require 'minitest/autorun'
require_relative '../src/issue-trackers'

ISSUE_TRACKER_TEST_DATA = <<TESTDATA
http://bugs.launchpad.net/bugs/1081676
https://bugreports.qt.io/browse/QTBUG-66897?attachmentSortBy=dateTime
https://bugreports.qt.io/browse/QTBUG-77115
https://bugreports.qt.io/browse/QTBUG-81542
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13734
https://bugs.documentfoundation.org/show_bug.cgi?id=79978
https://bugs.documentfoundation.org/show_bug.cgi?id=79978
https://bugs.freedesktop.org/show_bug.cgi?id=58380
https://bugs.freedesktop.org/show_bug.cgi?id=89600
https://bugs.kde.org/show_bug.cgi?id=379732
https://bugs.launchpad.net/cinder/+bug/1046985
https://bugs.launchpad.net/cinder/+bug/1046985
https://bugs.launchpad.net/kicad/+bug/1771003
https://bugs.launchpad.net/kicad/+bug/1826270
https://bugs.launchpad.net/kicad/+bug/1826278
https://bugs.launchpad.net/kicad/+bug/1826270
https://bugs.launchpad.net/kicad/+bug/1826278
https://bugs.launchpad.net/kicad/+bug/1826270
https://bugs.launchpad.net/kicad/+bug/1826278
https://bugs.launchpad.net/kicad/+bug/1826270
https://bugs.launchpad.net/qemu/+bug/1208944
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1333838
https://bugs.llvm.org/show_bug.cgi?id=45580
https://bugs.schedmd.com/show_bug.cgi?id=2807
https://bugs.schedmd.com/show_bug.cgi?id=2807
https://bugs.schedmd.com/show_bug.cgi?id=343
https://bugzilla.audacityteam.org/show_bug.cgi?id=2267
https://bugzilla.gnome.org/show_bug.cgi?id=720826
https://bugzilla.gnome.org/show_bug.cgi?id=750552
https://bugzilla.gnome.org/show_bug.cgi?id=753181
https://bugzilla.gnome.org/show_bug.cgi?id=753181
https://bugzilla.gnome.org/show_bug.cgi?id=761097
https://bugzilla.gnome.org/show_bug.cgi?id=761097
https://bugzilla.gnome.org/show_bug.cgi?id=761097
https://bugzilla.kernel.org/show_bug.cgi?id=50081
https://bugzilla.kernel.org/show_bug.cgi?id=50081
https://bugzilla.kernel.org/show_bug.cgi?id=50081
https://bugzilla.kernel.org/show_bug.cgi?id=50081
https://bugzilla.kernel.org/show_bug.cgi?id=50081
https://bugzilla.mozilla.org/show_bug.cgi?id=974554
https://bugzilla.redhat.com/1113474
https://bugzilla.redhat.com/show_bug.cgi?id=1113474
https://bugzilla.redhat.com/show_bug.cgi?id=1181444
https://bugzilla.redhat.com/show_bug.cgi?id=1190720
https://bugzilla.redhat.com/show_bug.cgi?id=1415609
https://bugzilla.redhat.com/show_bug.cgi?id=1113474
https://bugzilla.redhat.com/show_bug.cgi?id=1455825
https://bugzilla.tianocore.org/show_bug.cgi?id=1386
https://bugzilla.tianocore.org/show_bug.cgi?id=1387
https://bugzilla.tianocore.org/show_bug.cgi?id=1418
https://bugzilla.tianocore.org/show_bug.cgi?id=2137
https://bugzilla.tianocore.org/show_bug.cgi?id=2365
https://code.mythtv.org/trac/ticket/10071
https://code.mythtv.org/trac/ticket/10071
https://code.mythtv.org/trac/ticket/10071
https://dev.ib.pl/ib/otrs/issues/68
https://framagit.org/framasoft/Etherpad/ep_mypads/-/issues/166
https://github.com/0rpc/zerorpc-node/issues/11
https://github.com/agda/agda/issues/1388
https://github.com/agilgur5/react-signature-canvas/issues/11
https://github.com/aio-libs/aiohttp/issues/3595
https://github.com/akka/akka-http/issues/420
https://github.com/AlertaDengue/AlertaDengue/issues/170
https://github.com/analogdevicesinc/libiio/issues/73
https://github.com/analogdevicesinc/linux/issues/143
https://github.com/angular-ui/ui-select/issues/1617
https://github.com/angular-ui/ui-select/issues/1618
https://github.com/angular-ui/ui-select/issues/1617
https://github.com/angular-ui/ui-select/issues/1575
https://github.com/apache/bookkeeper/issues/907
https://github.com/apache/bookkeeper/issues/931
https://github.com/apache/bookkeeper/issues/931
https://github.com/apache/bookkeeper/issues/907
https://github.com/apache/bookkeeper/issues/931
https://github.com/apache/bookkeeper/issues/907
https://github.com/apache/bookkeeper/issues/931
https://github.com/apache/bookkeeper/issues/931
https://github.com/apache/bookkeeper/issues/907
https://github.com/apache/bookkeeper/issues/907
https://github.com/aquariuslt/blog/commit/324032f5b903855f96fbd150b771871ad398cbf6
https://github.com/aquariuslt/blog/commit/324032f5b903855f96fbd150b771871ad398cbf6
https://github.com/arduino/ArduinoCore-samd/issues/422
https://github.com/arduino/ArduinoCore-samd/issues/426
https://github.com/atari800/atari800/issues/89
https://github.com/Avalon-Team/Terraria-Avalon/issues/5
https://github.com/BabylonJS/Babylon.js/issues/2239
https://github.com/basho/bitcask/issues/82
https://github.com/BLAKE3-team/BLAKE3/issues/60#issuecomment-585838317
https://github.com/blinskey/greek-reference/issues/111
https://github.com/br101/horst/issues/47
https://github.com/Brainsware/puppet-trafficserver/issues/3
https://github.com/ceph/ceph/pull/5737
https://github.com/cernopendata/opendata.cern.ch/issues/357
https://github.com/chris2511/xca/issues/39
https://github.com/chris2511/xca/issues/39
https://github.com/chris2511/xca/issues/57
https://github.com/clips/pattern/issues/182
https://github.com/cloudyr/aws.s3/issues/142
https://github.com/cncjs/cncjs/issues/102
https://github.com/codemirror/CodeMirror/issues/4310
https://github.com/codinguser/gnucash-android/issues/479
https://github.com/commitizen/cz-cli/issues/153
https://github.com/COSIMA/access-om2/issues/163
https://github.com/cosmocode/dokuwiki-plugin-struct/issues/398
https://github.com/craftcms/cms/issues/1403
https://github.com/craftcms/cms/issues/1426
https://github.com/dalehenrich/filetree/issues/36
https://github.com/datajoint/datajoint-matlab/issues/2
https://github.com/DDMAL/cantus/issues/153
https://github.com/DDMAL/cantus/issues/117
https://github.com/DDMAL/cantus/issues/183
https://github.com/DDMAL/cantus/issues/182
https://github.com/dials/dials/issues/278
https://github.com/dials/dials/issues/278
https://github.com/dials/dials/issues/829
https://github.com/dimitri/pgloader/issues/124
https://github.com/dmtcp/dmtcp/issues/589
https://github.com/docdoku/docdoku-plm/issues/1000
https://github.com/duojs/duo/issues/474
https://github.com/duplicati/duplicati/issues/3460
https://github.com/DynamoRIO/dynamorio/issues/1551
https://github.com/DynamoRIO/dynamorio/issues/1686
https://github.com/DynamoRIO/dynamorio/issues/556
https://github.com/DynamoRIO/dynamorio/issues/975
https://github.com/DynamoRIO/dynamorio/pull/2856
https://github.com/DynamoRIO/dynamorio/pull/2636
https://github.com/DynareTeam/dynare/issues/1039
https://github.com/DynareTeam/dynare/issues/1184
https://github.com/eclipse/sumo/issues/21
https://github.com/eclipse/sw360/issues/762
https://github.com/emacs-helm/helm-cmd-t/issues/3
https://github.com/emacs-helm/helm/issues/1648
https://github.com/emacs-helm/helm/issues/1649
https://github.com/eschulte/epresent/issues/21
https://github.com/ESMCI/cime/issues/599
https://github.com/facebook/react/issues/6879
https://github.com/federicomariamassari/willowtree/issues/4
https://github.com/fish-shell/fish-shell/issues/4075
https://github.com/fish-shell/fish-shell/issues/4075
https://github.com/franko/luajit-lang-toolkit/issues/3
https://github.com/Freeyourgadget/Gadgetbridge/issues/643
https://github.com/fuel/core/issues/1123
https://github.com/fwupd/fwupd/issues/1770
https://github.com/fwupd/fwupd/issues/1770
https://github.com/GammaBurst101/GammaTimer/issues/1
https://github.com/garbagemule/MobArena/issues/557
https://github.com/gdh1995/vimium-c/issues/64
https://github.com/GemTalk/Rowan/issues/64
https://github.com/GeneAssembly/biosal/issues/709
https://github.com/GMOD/jbrowse/issues/357
https://github.com/GothenburgBitFactory/timewarrior/issues/293
https://github.com/groupon/roll/issues/11
https://github.com/haikuports/haikuporter/issues/83
https://github.com/hamishcoleman/thinkpad-ec/issues/9
https://github.com/hansec/fortran-language-server/issues/159
https://github.com/Homebrew/brew/issues/2657
https://github.com/hugsy/gef/issues/203
https://github.com/ifandelse/machina.js/issues/99
https://github.com/ifandelse/machina.js/issues/83
https://github.com/ifandelse/machina.js/issues/97
https://github.com/ifandelse/machina.js/issues/97
https://github.com/inasafe/inasafe/issues/2235
https://github.com/INRIA/spoon/issues/1053
https://github.com/IntelliTect/Coalesce/issues/119
https://github.com/inveniosoftware/invenio/issues/1330
https://github.com/ionic-team/ionic-framework/issues/1599
https://github.com/IQSS/dataverse/issues/4659
https://github.com/jbottel/TARS/issues/18
https://github.com/jbottel/TARS/issues/19
https://github.com/jbottel/TARS/issues/19
https://github.com/jeromewagener/Sammelbox/issues/85
https://github.com/jjjake/internetarchive/issues/30
https://github.com/JonnyJD/musicbrainz-isrcsubmit/issues/32
https://github.com/joshdick/miniProxy/issues/36
https://github.com/joyent/libuv/issues/754
https://github.com/jrblevin/markdown-mode/issues/193
https://github.com/JuliaLang/julia/issues/16529
https://github.com/jupyter/notebook/issues/917
https://github.com/kezabelle/django-shouty-templates/issues/1
https://github.com/Kong/kong/pull/3419
https://github.com/Kong/kong/pull/3300
https://github.com/kontrollanten/algolia-places-react/issues/93
https://github.com/koreader/koreader/issues/2477
https://github.com/LAHumphreys/ELf64-Linker/issues/15
https://github.com/larstvei/Try/issues/3
https://github.com/libKriging/libKriging/issues/16
https://github.com/lobid/lodmill/issues/533
https://github.com/magit/magit/issues/1732
https://github.com/magnumripper/JohnTheRipper/issues/3050
https://github.com/magnumripper/JohnTheRipper/issues/789
https://github.com/mangband/mangband/issues/1305
https://github.com/ManifoldScholar/manifold/issues/2378
https://github.com/mapbox/mbxmapkit/issues/56
https://github.com/markdownlint/markdownlint/issues/108
https://github.com/marklogic-community/RunDMC/issues/242
https://github.com/marklogic-community/RunDMC/issues/242
https://github.com/marklogic-community/RunDMC/issues/260
https://github.com/matomo-org/piwik-dotnet-tracker/issues/37
https://github.com/Matthimatiker/Erfurt/issues/13
https://github.com/mconf/mconf-web/issues/766
https://github.com/mcvine/mcvine/issues/157
https://github.com/MightyPirates/OpenComputers/issues/44
https://github.com/minio/minio/issues/7852
https://github.com/MLton/mlton/issues/305
https://github.com/monero-project/kovri/issues/305
https://github.com/mozilla/fxa-content-server/issues/219
https://github.com/mruby/mruby/issues/4513
https://github.com/myhdl/myhdl/issues/82
https://github.com/natebosch/vim-lsc/issues/188
https://github.com/necolas/react-native-web/issues/1512
https://github.com/NFFT/nfft/issues/72
https://github.com/ninuxorg/nodeshot/issues/210
https://github.com/nirizr/rematch/issues/323
https://github.com/nithinmurali/pygsheets/issues/139
https://github.com/NixOS/nixpkgs/issues/12403
https://github.com/nmellado/Super4PCS/issues/16
https://github.com/nodejs/node-v0.x-archive/issues/4626
https://github.com/nodejs/node/issues/14599
https://github.com/nodejs/node/issues/14599
https://github.com/nodejs/node/issues/14599
https://github.com/nodejs/node/issues/25870
https://github.com/nodejs/node/issues/25870
https://github.com/npm/npm/issues/1727
https://github.com/nrc-cnrc/EGSnrc/issues/257
https://github.com/nrc-cnrc/EGSnrc/issues/257
https://github.com/nydailynews/subway-stop-restaurant-lookup-table/issues/55
https://github.com/obspy/obspy/issues/903
https://github.com/ocornut/imgui/issues/1651
https://github.com/OpenFastPath/ofp/issues/93
https://github.com/OpenRC/openrc/issues/54
https://github.com/OpenRC/openrc/issues/54
https://github.com/openresty/lua-nginx-module/issues/1462
https://github.com/OpenSIPS/opensips/issues/1754
https://github.com/oscar-stack/vagrant-pe_build/issues/123
https://github.com/oscarlab/graphene/issues/80
https://github.com/OSGeo/gdal/issues/1472
https://github.com/OSGeo/gdal/issues/1472
https://github.com/OSGeo/gdal/issues/1535
https://github.com/pandemicsyn/statsdpy/issues/6
https://github.com/pantsbuild/pex/issues/82
https://github.com/pcolby/bipolar/issues/71
https://github.com/peelframework/peel/issues/96
https://github.com/Phrohdoh/easage/issues/19
https://github.com/PierreRaybaut/guiqwt/issues/24
https://github.com/pimcore/pimcore/issues/3104
https://github.com/pimcore/pimcore/issues/3104
https://github.com/PmagPy/PmagPy/issues/378
https://github.com/projectacrn/acrn-hypervisor/issues/3612
https://github.com/psychopy/psychopy/issues/1729
https://github.com/Puzzlout/FrameworkMvcLegacy/issues/22
https://github.com/ractivejs/ractive/issues/155
https://github.com/ralphlange/procServ/issues/18
https://github.com/raspberrypi/linux/issues/2617 ;https://github.com/raspberrypi/linux/issues/2617;
https://github.com/rclone/rclone/issues/1716
https://github.com/rclone/rclone/issues/2279
https://github.com/restic/restic/issues/1652
https://github.com/rstudio/rstudio/issues/1810
https://github.com/rstudio/rstudio/issues/1810
https://github.com/rubygems/rubygems/issues/1793
https://github.com/rubygems/rubygems/issues/1793
https://github.com/rust-lang/cargo/issues/1999
https://github.com/rust-lang/cargo/issues/1999
https://github.com/salt-formulas/salt-formula-helm/issues/8
https://github.com/SchizoDuckie/DuckieTV/issues/916
https://github.com/SCOREC/core/issues/45
https://github.com/scylladb/scylla-tools-java/issues/6
https://github.com/scylladb/scylla-tools-java/issues/6
https://github.com/sdlpal/sdlpal/issues/175
https://github.com/servalproject/serval-dna/issues/138
https://github.com/sidben/AtelierCanvas/issues/8
https://github.com/SonMinWoo/AnsanBladeWind/issues/8
https://github.com/SpareBank1/designsystem/issues/229
https://github.com/spring-projects/spring-boot/issues/18211
https://github.com/spring-projects/spring-framework/issues/14447
https://jira.spring.io/browse/SPR-14447?redirect=false
https://github.com/spring-projects/spring-framework/issues/19017
https://github.com/sqlitebrowser/sqlitebrowser/issues/1279
https://github.com/sqlitebrowser/sqlitebrowser/issues/1279
https://github.com/sqlitebrowser/sqlitebrowser/issues/1282
https://github.com/sqlitebrowser/sqlitebrowser/issues/1288
https://github.com/stan-dev/rstanarm/issues/376
https://github.com/supercollider/supercollider/issues/841
https://github.com/swanson/stringer/issues/436
https://github.com/swanson/stringer/issues/437
https://github.com/swanson/stringer/issues/436
https://github.com/swanson/stringer/issues/436
https://github.com/swanson/stringer/issues/437
https://github.com/swanson/stringer/issues/436
https://github.com/systemd/systemd/issues/11362
https://github.com/systemd/systemd/issues/11571
https://github.com/systemd/systemd/issues/11579
https://github.com/systemd/systemd/issues/11652
https://github.com/systemd/systemd/issues/12377
https://github.com/systemd/systemd/issues/12377
https://github.com/systemd/systemd/issues/12452
https://github.com/systemd/systemd/issues/7055
https://github.com/systemd/systemd/issues/7055
https://github.com/systemd/systemd/issues/7129
https://github.com/systopia/de.systopia.signatures/issues/6
https://github.com/tarantool/tarantool/issues/2541
https://github.com/tarantool/tarantool/issues/2541
https://github.com/tarantool/tarantool/issues/1906
https://github.com/tarantool/tarantool/issues/4672
https://github.com/tarantool/tarantool/issues/4672
https://github.com/tarantool/tarantool/issues/4672
https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/issues/53
https://github.com/Theano/Theano/issues/3377
https://github.com/thuehlinger/daemons/issues/22
https://github.com/toladata/TolaActivity/issues/668
https://github.com/toolbox-team/reddit-moderator-toolbox-legacy/issues/493
https://github.com/trezor/trezor-firmware/issues/448
https://github.com/trezor/trezor-firmware/issues/448
https://github.com/TrinityCore/TrinityCore/issues/23525
https://github.com/TrinityCore/TrinityCore/issues/23525
https://github.com/TypeCobolTeam/TypeCobol/issues/230
https://github.com/UniTime/unitime/issues/27
https://github.com/unshiftio/url-parse/issues/15
https://github.com/upgrades-migrations/preupgrade-assistant/issues/77
https://github.com/vatesfr/xen-orchestra/issues/3293
https://github.com/volatilityfoundation/volatility/issues/251
https://github.com/wanadev/PhotonUI/issues/58
https://github.com/wanadev/PhotonUI/issues/21
https://github.com/wanadev/PhotonUI/issues/21
https://github.com/wanadev/PhotonUI/issues/58
https://github.com/weaveworks/scope/issues/1304
https://github.com/wwwjfy/emacs-fish/issues/22
https://github.com/zephyrproject-rtos/zephyr/issues/23295
https://gitlab.com/gpsd/gpsd/-/issues/58
https://gitlab.com/mbukatov/pylatest/-/issues/15
https://gitlab.com/mbukatov/pylatest/issues/15
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2346
https://gitlab.freedesktop.org/mesa/mesa/issues/2346
https://gitlab.gnome.org/GNOME/gtk/issues/1316
https://gitlab.gnome.org/GNOME/gtk/-/issues/1316
https://issues.apache.org/jira/browse/KUDU-2229
https://issues.apache.org/jira/browse/KUDU-2229
https://issues.asterisk.org/jira/browse/ASTERISK-24917
https://issues.asterisk.org/jira/browse/ASTERISK-24917
https://issues.redhat.com/browse/JBEAP-9937?_sscc=t
https://jira.duraspace.org/browse/FCREPO-1095
https://jira.lyrasis.org/browse/FCREPO-1095
https://jira.duraspace.org/browse/FCREPO-946
https://jira.mongodb.org/browse/SERVER-14668
https://jira.percona.com/browse/FB8-212
https://jira.percona.com/browse/FB8-212
https://projects.theforeman.org/issues/24709
https://sourceforge.net/p/net-snmp/bugs/2294/
https://trac.sagemath.org/ticket/25494
https://trac.torproject.org/projects/tor/ticket/18517
https://trac.torproject.org/projects/tor/ticket/21596
https://tracker.ardour.org/view.php?id=7937
https://tracker.freecadweb.org/view.php?id=1740
https://www.redmine.org/issues/600
https://www.redmine.org/issues/670
TESTDATA


describe IssueTracker do
    it "should get a valid issue tracker for all the test URLs" do
        urls = ISSUE_TRACKER_TEST_DATA.split("\n").uniq
        
        urls.each do |url|
            handler = IssueTracker.handler_for(url)
            refute_nil handler
        end
    end
end
